// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkGzV9tFgkAuf1b2T8aLM13Q6kvP42y7k',
    appId: '1:737132298326:web:24a18d05be23a915c03bf7',
    messagingSenderId: '737132298326',
    projectId: 'exit-entry-system',
    authDomain: 'exit-entry-system.firebaseapp.com',
    storageBucket: 'exit-entry-system.firebasestorage.app',
    measurementId: 'G-FCXKT5QYCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2i45PjhhVureWCTT-pDBUHn2yyLxcPjc',
    appId: '1:737132298326:android:54f716c2c7bd294fc03bf7',
    messagingSenderId: '737132298326',
    projectId: 'exit-entry-system',
    storageBucket: 'exit-entry-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfz7E-U85xvJqByeuHzC5kae5eH_y8Cc8',
    appId: '1:737132298326:ios:249dc5121e8a2521c03bf7',
    messagingSenderId: '737132298326',
    projectId: 'exit-entry-system',
    storageBucket: 'exit-entry-system.firebasestorage.app',
    iosBundleId: 'com.example.exitEntrySystem',
  );
}
